// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storegen

import (
	"database/sql"
	"time"
)

type User struct {
	ID                 int32
	FirstName          string
	Surname            string
	CountryCode        string
	PhoneNumber        string
	FiatWalletCurrency string
	UsdcWalletAddress  sql.NullString
	UpdatedAt          time.Time
	ImageUrl           sql.NullString
	CreatedAt          time.Time
}
