// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package storegen

import (
	"database/sql"
)

type User struct {
	ID                 int32
	FirstName          string
	Surname            sql.NullString
	CountryCode        sql.NullString
	PhoneNumber        sql.NullString
	FiatWalletCurrency sql.NullString
	UsdcWalletAddress  sql.NullString
	UpdatedAt          sql.NullTime
	ImageUrl           sql.NullString
	CreatedAt          sql.NullTime
}
