version: '3'

# Taken from https://encore.dev/docs/develop/cli-reference
tasks:

  # Build Tasks
  check:
    desc: Checks your application for compile-time errors using Encore's compiler.
    cmds:
      - encore check

  run:
    desc: Runs your application. [--debug] [--watch=true] [flags]
    cmds:
      - encore run

  # Test
  test:
    desc: Run all unit tests.
    cmds:
      - encore test

  test-coverage:
    desc: Run unit tests with coverage reporting
    cmds:
      - encore test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  # Deployment
  deploy:
    desc: Deploy to production with Encore
    cmds:
      - git push encore

  # Other encore Specific Tasks
  logs:
    desc: Streams logs from your application [--env=prod] [--json]
    cmds:
      - encore logs

  encore-update:
    desc: Update encore CLI version
    cmds:
      - encore version update

  # Gen
  gen:
    desc: Run all generation commands, from bottom up
    deps:
      - gen-ts
      - sqlc-gen

  ## Client
  gen-ts:
    desc:  Generates an ts API client
    cmds:
      - encore gen client --env=local --output=frontend/gen/client.ts

  ## SQL generation
  sqlc-gen:
    desc: Regenerate all sqlc files
    deps:
      - sqlc-gen-usr
      - sqlc-gen-pay
      - sqlc-gen-wal

  sqlc-gen-usr:
    dir: users/store
    cmds:
      - sqlc generate

  sqlc-gen-pay:
    dir: payments/store
    cmds:
      - sqlc generate

  sqlc-gen-wal:
    dir: wallets/store
    cmds:
      - sqlc generate

 # DB
  db-local-str:
    desc: Get local DB connection string for given DB, e.g. 'task db-local-str -- users'
    cmds:
      - encore db conn-uri {{.CLI_ARGS}} --env=local

  db-stg-str:
    desc: Get staging DB connection string for given DB, e.g. 'task db-stg-str -- payments'
    cmds:
      - encore db conn-uri {{.CLI_ARGS}} --env=staging

  db-local-she:
    desc: Start a shell for given local DB,  e.g. 'task db-local-she -- wallets'
    cmds:
      - encore db shell {{.CLI_ARGS}} --env=local

  db-stg-she:
    desc: Start a shell for given staging DB,  e.g. 'task db-stg-she -- users'
    cmds:
      - encore db shell {{.CLI_ARGS}} --env=staging
