// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storegen

import (
	"context"
)

type Querier interface {
	InsertIntoPayments(ctx context.Context, arg InsertIntoPaymentsParams) (int32, error)
	LookupPaymentByReceiverId(ctx context.Context, receiverID string) ([]Payment, error)
	LookupPaymentByTxHash(ctx context.Context, txHash string) (Payment, error)
}

var _ Querier = (*Queries)(nil)
