// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storegen

import (
	"database/sql"
)

type Wallet struct {
	ID                  int32
	UserID              int32
	UsdcWalletAddress   string
	UsdcWalletAddressPk string
	CreatedAt           sql.NullTime
	UpdatedAt           sql.NullTime
	Assigned            bool
	UsdcBalance         float64
}
