// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storegen

import (
	"context"
)

type Querier interface {
	GetUnassignedWallet(ctx context.Context) (int32, error)
	InsertIntoWallets(ctx context.Context, arg InsertIntoWalletsParams) (int32, error)
	UpdateWallets(ctx context.Context, arg UpdateWalletsParams) (UpdateWalletsRow, error)
}

var _ Querier = (*Queries)(nil)
