// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storegen

import (
	"context"
)

type Querier interface {
	CountUnassignedWallets(ctx context.Context) ([]int64, error)
	GetUnassignedWallet(ctx context.Context) (int32, error)
	InsertIntoWallets(ctx context.Context, arg InsertIntoWalletsParams) (int32, error)
	LookupWallet(ctx context.Context, userID int32) (LookupWalletRow, error)
	LookupWalletBalance(ctx context.Context, userID int32) (float64, error)
	UpdateWalletBalance(ctx context.Context, arg UpdateWalletBalanceParams) error
	UpdateWallets(ctx context.Context, arg UpdateWalletsParams) (UpdateWalletsRow, error)
}

var _ Querier = (*Queries)(nil)
