// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package storegen

import (
	"context"
)

const getUnassignedWallet = `-- name: GetUnassignedWallet :one
SELECT id
FROM wallets
WHERE assigned = FALSE
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetUnassignedWallet(ctx context.Context) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUnassignedWallet)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const insertIntoWallets = `-- name: InsertIntoWallets :one
INSERT INTO wallets (user_id, usdc_wallet_address, usdc_wallet_address_pk, usdc_balance)
VALUES ($1 :: INT,
        $2 :: VARCHAR(44),
        $3 :: VARCHAR(88),
        $4 :: FLOAT)
RETURNING id
`

type InsertIntoWalletsParams struct {
	UserID              int32
	UsdcWalletAddress   string
	UsdcWalletAddressPk string
	UsdcBalance         float64
}

func (q *Queries) InsertIntoWallets(ctx context.Context, arg InsertIntoWalletsParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, insertIntoWallets,
		arg.UserID,
		arg.UsdcWalletAddress,
		arg.UsdcWalletAddressPk,
		arg.UsdcBalance,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateWallets = `-- name: UpdateWallets :one
UPDATE wallets
SET updated_at = CURRENT_TIMESTAMP AT TIME ZONE 'UTC',
    user_id    = COALESCE($1, user_id),
    assigned   = COALESCE($2, assigned)
WHERE id = $3 :: INT
RETURNING id
    , usdc_wallet_address
`

type UpdateWalletsParams struct {
	UserID   int32
	Assigned bool
	ID       int32
}

type UpdateWalletsRow struct {
	ID                int32
	UsdcWalletAddress string
}

func (q *Queries) UpdateWallets(ctx context.Context, arg UpdateWalletsParams) (UpdateWalletsRow, error) {
	row := q.db.QueryRowContext(ctx, updateWallets, arg.UserID, arg.Assigned, arg.ID)
	var i UpdateWalletsRow
	err := row.Scan(&i.ID, &i.UsdcWalletAddress)
	return i, err
}
